---
#
# Role used to install a basic Matrix synapse server
# The configuration of the server will be completed later in synapse-extra-config role
#
- name: Add ananace-charts helm repository
  kubernetes.core.helm_repository:
    name: ananace-charts
    repo_url: "https://ananace.gitlab.io/charts"

- name: Is synapse already running?
  kubernetes.core.k8s_info:
    kind: Deployment
    name: matrix-synapse
    namespace: default
  register: synapse_deployment

- name: Get replicaset number
  set_fact:
    synapse_was_already_running: "{{ synapse_deployment.resources[0].status.replicas | default(0) }}"

- name: Display synapse status
  debug:
    var: synapse_was_already_running

- name: matrix-synapse helm chart
  kubernetes.core.helm:
    name: matrix-synapse
    chart_ref: ananace-charts/matrix-synapse
    chart_version: "{{ matrix.chart_version }}"
    release_state: "{{ absent_or_present }}"
    release_namespace: default
    values: "{{ lookup('template', 'synapse-chart-config.j2') | from_yaml }}"
    update_repo_cache: yes

- name: Wait for the synapse instance to be up and running
  ansible.builtin.uri:
    url: "https://{{ matrix.server_name }}/_matrix/static/"
    method: GET
  register: synapse_ping
  until: synapse_ping.status==200
  retries: 30
  delay: 5
  when: absent_or_present=="present"
