---
- name: install element-web helm chart
  kubernetes.core.helm:
    name: element-web
    chart_ref: ananace-charts/element-web
    chart_version: "{{ element.chart_version }}"
    release_state: "{{ absent_or_present }}"
    release_namespace: element-web
    create_namespace: true
    release_values:
      defaultServer:
        url: "https://{{ matrix.server_name }}"
        name: "{{ matrix.server_name }}"
        #  if not set or "", helm chart sets it to vector.im. Space here avoids overriding configuration along with the identity server unreachable warning on login page
        identity_url: " "
      nginxConfig: |-
        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Content-Security-Policy "frame-ancestors 'self'";
      config:
        logout_redirect_url: "https://{{ keycloak.server_name }}/realms/eimis-realm/protocol/openid-connect/logout?post_logout_redirect_uri=https://{{ element.server_name }}&client_id={{ keycloak.client_id }}"
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 100m
          memory: 128Mi
      ingress:
        enabled: true
        className: nginx
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
        hosts:
          - "{{ element.server_name }}"
        tls:
          - hosts:
              - "{{ element.server_name }}"
            secretName: "element-tls-secret"
      extraConfig:
        enable_registration: false
        enable_registration_without_verification: false
    update_repo_cache: yes
