apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: matrix-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
  endpoints:
    - port: metrics
      path: /_synapse/metrics
  namespaceSelector:
    any: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
