---
- name: Install basic packages
  apt:
    name:
      - ca-certificates
      - curl
      - python3
      - python3-pip
      - python3-netaddr
      - acl
    state: present
    update_cache: True
