---
- name: Install basic packages
  apt:
    name:
      - ca-certificates
      - curl
      - python3
      - python3-pip
      - python3-netaddr
    state: present
    update_cache: True

#- name: "Installing Python module"
#  pip:
#    name: netaddr