---
# Installs and configures all the components needed for synapse
- hosts: localhost
  vars:
    absent_or_present: present
  roles:
    - check
    - ingress-controller
    - cert-manager
    - keycloak-operator
    - postgresql-init
    - keycloak
    - teams-bridge
    - stunner
    - synapse
    - first-admin
    - auth-buttons
    - discovery-rooms
    - cgu-room
    - synapse-extra-config
    - element-web
    - monitoring
