---
collections:
  - name: kubernetes.core
    version: 2.4.2
  - name: community.zabbix
    version: 2.4.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.postgresql
    version: 3.4.0
  - name: community.general
    version: 8.6.0
  - name: ansible.netcommon
    version: 5.3.0
  - name: community.docker
    version: 3.10.3
