---
- name: Add ingress-nginx helm repository
  kubernetes.core.helm_repository:
    name: ingress-nginx
    repo_url: "https://kubernetes.github.io/ingress-nginx"

- name: install ingress-nginx helm chart
  kubernetes.core.helm:
    name: ingress-nginx
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_controller.version }}"
    release_namespace: ingress-nginx
    create_namespace: true
    update_repo_cache: yes
    values:
      service:
        enable: false

- name: Add ingress-nginx controller service
  kubernetes.core.k8s:
    state: present
    template: "ingress-nginx-service.yml"
