- name: Add ingress-nginx controller
  kubernetes.core.k8s:
    state: present
    template: "ingress-nginx.yml"

- name: Get the ingress-controller external IP
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: ingress-nginx-controller
    namespace: ingress-nginx
  register: ingress_controller_service
  until: ingress_controller_service.resources[0].spec.ports[0].nodePort is defined
  retries: 10
  delay: 10
